language: node_js
node_js:
  - "8"
  - "9",
  - "10"
env:
  - NODE_ENV="local"
before_install:
  - npm i chai --save
  - npm i eslint-config-daniels --save
  - npm i mocha --save
  - npm i nyc --save
install:
  - npm i
script:
  - npm run lint
  - npm run test
after_script:
  - npm run build
